language: python

python:
    - "3.6"

install:
    - python3 setup.py install

script:
    - pip install pipenv
    - pipenv install --dev
    - pipenv run flake8
    - pipenv run mypy flake8_alfred
    - pipenv run pytest
